### ISSUE TITLE
Scheme should be 'https', but is 'http'.

### ISSUE THREAD

**Issue by hexagon6** [manomayam/manas#34]
I try to use manas as storage pod.

For this I set up manas with tls-certificates in my local network.

When using `https://myhost/resource` as reference for a solid document from my solid application I get a http 400 error in the browser console / fetching from web client.

Client log looks like this:

```
Error: Fetching the Resource at [https://myhost/resource] failed: [400] [] {"type":"https://httpstatuses.com/400","status":400,"title":"Bad Request","detail":"Invalid request target"}.
```

Server log looks like this:

```stdout
  2023-11-06T09:50:07.195644Z DEBUG manas_http::service::impl_::reconstruct_target_uri: Target uri builder: Builder { scheme: Some("http"), authority: None, path: "/", query: None, fragment: None, normalize: false }
    at crates/manas_http/src/service/impl_/reconstruct_target_uri.rs:140

  2023-11-06T09:50:07.195917Z ERROR manas_http::service::impl_::reconstruct_target_uri: Error in reconstructing target uri.
    at crates/manas_http/src/service/impl_/reconstruct_target_uri.rs:155
```

Tracing back the error it looks to me the scheme variable is initialized with 'http' and only updated when Forward-headers are present. In my setup this is not the case (no reverse-proxy setting those I assume).

So maybe something is either wrong in the logic of https://github.com/manomayam/manas/blob/9eb1fb2003af8bcdc673b2dc5b6672a63f63e10a/crates/manas_http/src/service/impl_/reconstruct_target_uri.rs#L86 or I need to change something on my setup so the default scheme is initialized as 'https'.

**Comment by hexagon6** [comment]
My config.toml looks like this:

```toml
[storage.space]
# Uri of the storage root.
root_uri = "https://myhost/"
```

**Comment by damooo** [comment]
You  have to specify tls configuraion in config.toml, and  also should bind to correct port. Can you post full `config.toml` with dummy secrets?
```toml
[server.tls]
# Cert pem file path.
cert_path = "/path/to/cert.pem"

# Key pem file path.
key_path = "/path/to/key.pem"
```

**Comment by damooo** [comment]
Oh, issue seems here:
https://github.com/manomayam/manas/blob/9eb1fb2003af8bcdc673b2dc5b6672a63f63e10a/crates/manas_server/src/recipe/impl_/common/mod.rs#L48

Recipe is not passing the config down to the service. I should push fix soon.

Thanks for the report.

**Comment by hexagon6** [comment]
I tolerate it of course. :) Thank you very much for your work! I am looking forward to use manas on a daily basis and keep testing for you.

**Comment by damooo** [comment]
I pushed the fix, will release binary shortly, along with http-signatures support.
Working on also integrating a production ready identity provider, so that dev setup can be complete.

**Comment by hexagon6** [comment]
I compiled the latest version and Scheme has changed as expected to https:

```log
  2023-11-08T17:27:40.170084Z DEBUG manas_http::service::impl_::reconstruct_target_uri: Target uri builder: Builder { scheme: Some("https"), authority: None, path: "/manas", query: None, fragment: None, normalize: false }
    at crates/manas_http/src/service/impl_/reconstruct_target_uri.rs:140

  2023-11-08T17:27:40.170457Z ERROR manas_http::service::impl_::reconstruct_target_uri: Error in reconstructing target uri.
    at crates/manas_http/src/service/impl_/reconstruct_target_uri.rs:155
```

Unfortunately I still get http 400 response as the second error show. Shall I open another issue specific to this or can we continue here?

**Comment by damooo** [comment]
Wierd that `authority` is `None`. It is directly parsed from the request headers. I will once check for the possible reason. Can you specify the full `Config.toml` once?

**Comment by hexagon6** [comment]
The request header looks like this:

```
authorization | DPoP e.....tQ <long string redacted>
```

**Comment by damooo** [comment]
can  you once check with latest changes in [`jsonld-http-loader`](https://github.com/manomayam/manas/tree/jsonld-http-loader) branch? Thanks a lot.

**Comment by hexagon6** [comment]
> can you once check with latest changes in [`jsonld-http-loader`](https://github.com/manomayam/manas/tree/jsonld-http-loader) branch? Thanks a lot.

Will do! Building at once

**Comment by hexagon6** [comment]
Running cargo build fails (with some unused imports warnings, but posting only the error here):

```
...
   Compiling manas_http v0.1.1 (/home/user/projects/github.com/manas/crates/manas_http)
error[E0432]: unresolved import `smallvec`
  --> crates/manas_http/src/representation/metadata/derived_etag.rs:14:5
   |
14 | use smallvec::SmallVec;
   |     ^^^^^^^^ use of undeclared crate or module `smallvec`

   Compiling sha3 v0.10.8
   Compiling aes-gcm v0.10.3
For more information about this error, try `rustc --explain E0432`.
error: could not compile `manas_http` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by damooo** [comment]
Sorry. Must work now with code in the branch. A new crate [`http_typed_headers`] been extracted there. Dependency update issue.

And the reason for no-authority error is that, `hyper` doesn't provide a normalized `Host` header for http2. For http2 we have to extract authority from the request-target uri instead. It was manifested for https, as browsers defaults to http2. Here is the new code:

https://github.com/manomayam/manas/blob/72f37ba33216ce2257e849fcd1a594a3d3942b99/crates/manas_http/src/service/impl_/reconstruct_target_uri.rs#L85-L95

Also, i added you to contributors list in `README`. Thanks a lot.

**Comment by hexagon6** [comment]
Great! Which commit shall I test specifically? I can build from any, no need to track branches. I would recommend you make smaller commits, this makes it easier to revert or cherry-pick if something breaks (of course in this early development phase this might not be desirable to go fast).

**Comment by damooo** [comment]
This branch's latest commit: https://github.com/manomayam/manas/tree/jsonld-http-loader

That branch is used to add support for json-ld, and current fixes also in that. Changes to main branch must be only merged from prs.

**Comment by hexagon6** [comment]
Requests now extract the authorization correctly. I guess this can be closed.
I will open another issue for a thing that does not work yet, but will test again once your work in this branch has merged into main. :-) (hint: `http 415`: Unsupported media type **Unsupported patch document type.**)

**Comment by damooo** [comment]
> extract the authorization correctly
Not `authorization`, but `authority`, a component of http uris. I.e. host_address + port info.

**Comment by hexagon6** [comment]
> > extract the authorization correctly
> 
> Not `authorization`, but `authority`, a component of http uris. I.e. host_address + port info.

Ok, I did not know that. 🙏

> > extract the authorization correctly
> 
> Not `authorization`, but `authority`, a component of http uris. I.e. host_address + port info.

🙏 Thank you for clarification.

**Comment by damooo** [comment]
@hexagon6 

Now json-ld support is added to `Manas`. Could you open the new issue for the problem you encountered?

Thank you.

**Comment by hexagon6** [comment]
I compiled it and it works. Will open an issue and update this comment with link
